
version: '3'
services:
  compiler:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - MEMORY_LIMIT=512000
      - TIME_LIMIT=2000
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    restart: unless-stopped

